language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_VERSION=2.8.*

before_install:
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate

install: composer install

script: phpunit --configuration app/phpunit.xml
