language: php

php:
    - 5.5
    - 5.6

services:
  - mysql

env:
  - SYMFONY_VERSION=2.8.*

before_install:
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com "$GH_TOKEN"; fi;
  - mysql -e "CREATE USER 'capo'@'127.0.0.1' IDENTIFIED BY 'djikjdioue23io4ueiodwjdioq932108329edjka;';"

install: composer install --no-interaction

script: phpunit --configuration app/phpunit.xml
