language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

script: phpunit --configuration app/phpunit.xml

