language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_VERSION=2.7.*

before_install:
  - composer selfupdate

before_script:
    - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

install: composer update --prefer-dist --no-interaction

script: phpunit --configuration app/phpunit.xml
