imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    session:         
        save_path:  "/var/lib/capo/sessions"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

fr3d_ldap:
    client:
        host:         "%ldap_host%"
        useStartTls:  false # Enable TLS negotiation. Optional
        port:         389    # Optional
        version:        3    # Optional
        username:    "%ldap_user%"
        password:    "%ldap_password%"
#       username:     foo    # Optional
#       password:     bar    # Optional
        optReferrals: false  # Optional
        useSsl:       false   # Enable SSL negotiation. Optional
#       useStartTls:  true   # Enable TLS negotiation. Optional
    user:
        #baseDn: ou=users, dc=host, dc=foo
        #baseDn: uid=<username>,ou=People,dc=as9143,dc=internal
        baseDn: "%ldap_basedn%"
        #filter: (&(ObjectClass=user))
        filter:
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
            - { ldap_attr: samaccountname,  user_method: setUsername } # Default
            - { ldap_attr: dn,  user_method: setLdapGroup }
#           - { ldap_attr: cn,   user_method: setName }     # Optional
#           - { ldap_attr: ...,  user_method: ... }         # Optional
    service:
        user_manager: fos_user.user_manager          # Overrides default user manager
        ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Gizmo\CapoBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


