imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        #path:     :memory:
        #path: %kernel.cache_dir%/test.db
        path: /tmp/test.db
        #memory:  true
        memory:   false
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true

security:
    firewalls:
        main:
            security: false

fr3d_ldap:
    driver: ~
    user: ~
    service: ~

parameters:
    enable_eventlog: no
