imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    templating:
        engines:
            - twig
    session:
        save_path:  "%kernel.root_dir%/var/sessions"
    assets:
        version:    20150610001

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

fr3d_ldap:
    driver:
        host:         "%ldap_host%"
        useStartTls:  false # Enable TLS negotiation. Optional
        port:         389    # Optional
        username:    "%ldap_user%"
        password:    "%ldap_password%"
#       username:     foo    # Optional
#       password:     bar    # Optional
        optReferrals: false  # Optional
        useSsl:       false   # Enable SSL negotiation. Optional
#       useStartTls:  true   # Enable TLS negotiation. Optional
        bindRequiresDn: true
        accountFilterFormat: '(&(sAMAccountName=%%s))'
    user:
        baseDn: "%ldap_basedn%"
        usernameAttribute: sAMAccountName
        filter: (&(ObjectClass=user))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
            - { ldap_attr: samaccountname,  user_method: setUsername } # Default
            - { ldap_attr: distinguishedname,  user_method: setLdapGroup }
#           - { ldap_attr: cn,   user_method: setName }     # Optional
#           - { ldap_attr: ...,  user_method: ... }         # Optional
    service:
        ldap_manager: fr3d_ldap.ldap_manager.default # Overrides default ldap manager

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Gizmo\CapoBundle\Entity\User

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
