fos_user_security:
  resource: "@GizmoCapoBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

gizmo_capo_homepage:
    path:  /
    defaults: { _controller: GizmoCapoBundle:Default:index }

gizmo_capo_weathermaps:
    path:  /weathermaps/
    defaults: { _controller: GizmoCapoBundle:Default:weathermaps }

gizmo_capo_settings_index:
    path:  /settings/index/
    defaults: { _controller: GizmoCapoBundle:Settings:index}
gizmo_capo_settings_saved_selections:
    path:  /settings/saved_selections/
    defaults: { _controller: GizmoCapoBundle:Settings:savedSelections}
gizmo_capo_settings_cacti_instances:
    path:  /settings/cacti_instances/
    defaults: { _controller: GizmoCapoBundle:Settings:cactiInstances}
gizmo_capo_settings_users:
    path:  /settings/users/
    defaults: { _controller: GizmoCapoBundle:Settings:userAccess}
gizmo_capo_settings_groups:
    path:  /settings/groups/
    defaults: { _controller: GizmoCapoBundle:Settings:groupAccess}
gizmo_capo_settings_event_log:
    path:  /settings/event_log/
    defaults: { _controller: GizmoCapoBundle:Settings:eventLog}
gizmo_capo_settings_api_accounts:
    path:  /settings/api_accounts/
    defaults: { _controller: GizmoCapoBundle:Settings:apiAccounts}

gizmo_capo_pdf_graph:
    path:  /pdf/single_graph/
    defaults: { _controller: GizmoCapoBundle:Pdf:pdfSingleGraph}
gizmo_capo_pdf:
    path:  /pdf/graph_selection/
    defaults: { _controller: GizmoCapoBundle:Pdf:pdfGraphSelection}

gizmo_capo_api_show_graph:
    path: /api/show_graph/{graph_id}/{rra_id}/
    defaults: { _controller: GizmoCapoBundle:Api:showGraph }
    requirements:
        graph_id: \d+
        rra_id: \d+
gizmo_capo_api_show_graph_dated:
    path: /api/show_graph/{graph_id}/{rra_id}/{graph_start}/{graph_end}/
    defaults: { _controller: GizmoCapoBundle:Api:showGraph, graph_start: null, graph_end: null}
    requirements:
        graph_id: \d+
        rra_id: \d+
        graph_start: \d+
        graph_end: \d+
gizmo_capo_api_show_wmap:
    path: /api/show_wmap/{wmap_id}/
    defaults: { _controller: GizmoCapoBundle:Api:showWmap}
    requirements:
        wmap_id: \d+
gizmo_capo_api_get_cacti_instances:
    path: /api/get_cacti_instances/
    defaults: { _controller: GizmoCapoBundle:Api:getCactiInstances}
gizmo_capo_api_get_graph:
    path: /api/get_graph/
    defaults: { _controller: GizmoCapoBundle:Api:getGraph}
gizmo_capo_api_get_graphs:
    path: /api/get_graphs/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphs}
gizmo_capo_api_get_graph_selections:
    path: /api/get_graph_selections/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphSelections}
gizmo_capo_api_get_graph_selection_graphs:
    path: /api/get_graph_selection_graphs/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphSelectionGraphs}
gizmo_capo_api_save_graph_selection:
    path: /api/save_graph_selection/
    defaults: { _controller: GizmoCapoBundle:Api:saveGraphSelection}
gizmo_capo_api_disable_graph_selection:
    path: /api/disable_graph_selection/
    defaults: { _controller: GizmoCapoBundle:Api:disableGraphSelection}
gizmo_capo_api_rename_graph_selection:
    path: /api/rename_graph_selection/
    defaults: { _controller: GizmoCapoBundle:Api:renameGraphSelection}
gizmo_capo_api_change_graph_selection_item_itemnr:
    path: /api/graph_selection/item/reposition/
    defaults: { _controller: GizmoCapoBundle:Api:changeGraphSelectionItemItemNr}
gizmo_capo_api_get_graph_titles:
    path: /api/get_graph_titles/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphTitles}
gizmo_capo_api_get_graph_templates:
    path: /api/get_graph_templates/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphTemplates}
gizmo_capo_api_get_hosts:
    path: /api/get_hosts/
    defaults: { _controller: GizmoCapoBundle:Api:getHosts}
gizmo_capo_api_get_weathermaps:
    path: /api/get_weathermaps/
    defaults: { _controller: GizmoCapoBundle:Api:getWeathermaps}

gizmo_capo_api_admin_get_users:
    path: /api/admin/get_users/
    defaults: { _controller: GizmoCapoBundle:AdminApi:getUsers}

gizmo_capo_api_admin_user_change_group:
    path: /api/admin/user/change_group/
    defaults: { _controller: GizmoCapoBundle:AdminApi:changeGroupForUser}

gizmo_capo_api_admin_get_groups:
    path: /api/admin/get_groups/
    defaults: { _controller: GizmoCapoBundle:AdminApi:getGroups}

gizmo_capo_api_admin_get_api_accounts:
    path: /api/admin/get_api_accounts/
    defaults: { _controller: GizmoCapoBundle:AdminApi:getApiAccounts}

gizmo_capo_api_admin_get_eventlog:
    path: /api/admin/get_event_log/
    defaults: { _controller: GizmoCapoBundle:AdminApi:getEventLog}

gizmo_capo_api_admin_get_cacti_instances:
    path: /api/admin/get_cacti_instances/
    defaults: { _controller: GizmoCapoBundle:AdminApi:getCactiInstances}

gizmo_capo_api_admin_enable_cacti_instance_for_group:
    path: /api/admin/enable_cacti_instance_for_group/
    defaults: { _controller: GizmoCapoBundle:AdminApi:enableCactiInstanceForGroup}

gizmo_capo_api_admin_disable_cacti_instance_for_group:
    path: /api/admin/disable_cacti_instance_for_group/
    defaults: { _controller: GizmoCapoBundle:AdminApi:disableCactiInstanceForGroup}

gizmo_capo_api_admin_enable_cacti_instance_for_api_user:
    path: /api/admin/enable_cacti_instance_for_api_user/
    defaults: { _controller: GizmoCapoBundle:AdminApi:enableCactiInstanceForApiUser}

gizmo_capo_api_admin_disable_cacti_instance_for_api_user:
    path: /api/admin/disable_cacti_instance_for_api_user/
    defaults: { _controller: GizmoCapoBundle:AdminApi:disableCactiInstanceForApiUser}

gizmo_capo_api_admin_update_cacti_instance:
    path: /api/admin/cacti_instance/update/
    defaults: { _controller: GizmoCapoBundle:AdminApi:updateCactiInstance}

gizmo_capo_api_admin_create_cacti_instance:
    path: /api/admin/cacti_instance/create/
    defaults: { _controller: GizmoCapoBundle:AdminApi:createCactiInstance}

gizmo_capo_api_admin_create_group:
    path: /api/admin/group/create/
    defaults: { _controller: GizmoCapoBundle:AdminApi:createGroup}

gizmo_capo_api_admin_create_api_user:
    path: /api/admin/api_user/create/
    defaults: { _controller: GizmoCapoBundle:AdminApi:createApiUser}

gizmo_capo_api_admin_update_group:
    path: /api/admin/group/update/
    defaults: { _controller: GizmoCapoBundle:AdminApi:updateGroup}

gizmo_capo_api_admin_update_api_user:
    path: /api/admin/api_user/update/
    defaults: { _controller: GizmoCapoBundle:AdminApi:updateApiUser}

gizmo_capo_api_admin_update_user:
    path: /api/admin/user/update/
    defaults: { _controller: GizmoCapoBundle:AdminApi:updateUser}

gizmo_capo_api_external_get_cacti_instances:
    path: /srv/get_cacti_instances/
    defaults: { _controller: GizmoCapoBundle:Api:getCactiInstances}
gizmo_capo_api_external_get_graphs:
    path: /srv/get_graphs/
    defaults: { _controller: GizmoCapoBundle:Api:getGraphs}
gizmo_capo_api_external_get_graph:
    path: /srv/get_graph/
    defaults: { _controller: GizmoCapoBundle:Api:getGraph}
gizmo_capo_api_external_show_graph:
    path: /srv/show_graph/{graph_id}/{rra_id}/
    defaults: { _controller: GizmoCapoBundle:Api:showGraph }
    requirements:
        graph_id: \d+
        rra_id: \d+
