parameters:
#    gizmo_capo.example.class: Gizmo\CapoBundle\Example

services:
    pdf_exporter:
        class:  Gizmo\CapoBundle\Services\PDFService
        calls:
            - [ setTitle, [ 'Capo PDF Export', true ] ]
            - [ setLogoPath, [ "Resources/public/images/logo.png" ] ]

    event_logger:
        class:  Gizmo\CapoBundle\Services\EventLogService
        arguments: ['@security.token_storage', '@doctrine', %enable_eventlog%]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    xml_conversion:
        class:  Gizmo\CapoBundle\Services\XmlConversionService
