parameters:
#    gizmo_capo.example.class: Gizmo\CapoBundle\Example

services:
    wsse.security.authentication.provider:
        class:  Gizmo\CapoBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    wsse.security.authentication.listener:
        class:  Gizmo\CapoBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]

    pdf_exporter:
        class:  Gizmo\CapoBundle\Services\PDFService
        calls:
            - [ setTitle, [ 'Capo PDF Export', true ] ]
            - [ setLogoPath, [ "Resources/public/images/logo.png" ] ]

    event_logger:
        class:  Gizmo\CapoBundle\Services\EventLogService
        arguments: ['@security.context', '@doctrine', %enable_eventlog%]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    xml_conversion:
        class:  Gizmo\CapoBundle\Services\XmlConversionService
